### PR TITLE
Improved Variable Names

### PR DESCRIPTION
**Pull request by Joshua-Miles**
I found the naming of a few of these variables to be confusing for students, as character_hash was not actually a hash that represented a character. It was a hash that represented an api response, which included an array of character hashes.

### CODE REVIEW

**Comment by realAndrewCohn** [comment]
addresses #6

**Review by realAndrewCohn — APPROVED** [review]
image

**Comment by sgharms** [comment]
@Joshua-Miles 

Clear improvement.

I'm a bit worried that they'll infer that naming vars `_hash` or `_array` is a good naming practice though (and you said no one would miss Java....). Could you add:

> **NOTE** in this demonstration we name many of the variables `_hash` or `_array`. This is done for educational purposes. This is not typically done in code. 

Wherever you see fit.

And then merge as you see fit.

**Review by sgharms — CHANGES_REQUESTED** [review]
@Joshua-Miles

Clear improvement.

I'm a bit worried that they'll infer that naming vars _hash or _array is a good naming practice though (and you said no one would miss Java....). Could you add:

NOTE in this demonstration we name many of the variables _hash or _array. This is done for educational purposes. This is not typically done in code.

Wherever you see fit.

And then merge as you see fit.

**Pull request merged**
